# Generated by Django 5.1.2 on 2024-10-14 00:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categorie_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactions_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=30)),
                ('transaction_date', models.DateField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('S', 'SalesPerson')], max_length=1)),
                ('phone_number', models.IntegerField()),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('adress', models.TextField(max_length=500)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
                ('loan_status', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('bar_code', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('quality', models.IntegerField()),
                ('categorie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('sales_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.admin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.product')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.sales')),
            ],
        ),
    ]
