# Generated by Django 5.1.2 on 2024-10-19 10:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(default='Cash', max_length=30)),
                ('transaction_date', models.DateField(default=datetime.datetime.now)),
                ('total_amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('S', 'SalesPerson')], default='S', max_length=1)),
                ('phone_number', models.BigIntegerField()),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField(max_length=500)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
                ('loan_status', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('previous_amount', models.IntegerField(default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('total_amount', models.IntegerField(default=0)),
                ('payement_type', models.CharField(default='Cash', max_length=30)),
                ('sales_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.admin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('bar_code', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('quality', models.IntegerField(default=1)),
                ('categorie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('total_amount', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='genfin.product')),
                ('sales_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.admin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.customer')),
                ('transactions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genfin.transactions')),
            ],
        ),
    ]
