# Generated by Django 5.1.2 on 2024-11-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorie_name',
            field=models.CharField(max_length=200),
        ),
    ]
