# Generated by Django 5.1.2 on 2024-10-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
