# Generated by Django 5.1.2 on 2024-11-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0002_alter_categories_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
