# Generated by Django 5.1.2 on 2024-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0011_alter_item_sales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorie_name',
            field=models.CharField(max_length=300),
        ),
    ]
