# Generated by Django 5.1.2 on 2024-11-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0012_alter_categories_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorie_name',
            field=models.CharField(max_length=500),
        ),
    ]
