# Generated by Django 5.1.2 on 2024-11-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0013_alter_categories_categorie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sales_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
