# Generated by Django 5.1.2 on 2024-11-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0014_remove_item_sales_id_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itesms',
            field=models.JSONField(default=list),
        ),
    ]
