# Generated by Django 5.1.2 on 2024-11-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0015_item_itesms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itesms',
        ),
    ]
