# Generated by Django 5.1.2 on 2024-11-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0016_remove_item_itesms'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sales_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='genfin.sales'),
        ),
    ]
