# Generated by Django 5.1.2 on 2024-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0018_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sales', 'SalesPerson')], default='user', max_length=10),
        ),
        migrations.RemoveField(
            model_name='sales',
            name='items',
        ),
        migrations.AddField(
            model_name='sales',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
