# Generated by Django 5.1.2 on 2024-11-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfin', '0019_alter_admin_role_remove_sales_items_sales_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
    ]
