INSERT INTO generalfinance.genfin_categories (categorie_name) VALUES 
('Crockery'),
('Insecticides'),
('Toilet Soaps'),
('Tooth Paste'),
('OTC Products'),
('Nimko'),
('Fast Food'),
('bath Assets'),
('Baygons'),
('Detergents Dish Wash/Dish wash Bar'),
('Bleach Phenyl Cleaners blue liquid'),
('Toilet Cleaner'),
('Pulses'),
('Spices / Salt'),
('Green Tea'),
('Cereals'),
('Chocolates Toffees Sweets'),
('Dessert (Custard Cereals Kheer, Pudding)'),
('Creams/Vasline'),
('Hair Oil/Color/Gel'),
('Hair Shampoos'),
('Baby powder'),
('Washing soap'),
('Liquid Blach / Liquid blue'),
('Washing Powder'),
('Commodities'),
('Dustbin'),
('Toilet Rolls,Tissues'),
('Ketchup Pickles Sauce Vinegar'),
('Tooth Brushes'),
('Baby DIAPERS/Baby Wipes'),
('Dusters'),
('STRAINER'),
('Shoes Polish/Shoes Brush'),
('Dish wash bar'),
('Miscellaneous'),
('Phenyl'),
('Cloth Brush'),
('Cloth clips'),
('Non Food'),
('Towels'),
('Tea'),
('Cakes'),
('Hand wash Hand Sanitizer Face wash'),
('All'),
('Milk Powders'),
('Ispaghol'),
('MOSQUITO OIl'),
('Toilt Brush'),
('Stationery Items'),
('Garnier'),
('Gillette'),
('Glass cleaner'),
('Golden country Food'),
('House Holds'),
('Hanger'),
('Pencils'),
('Hand wash'),
('Iodized Salt'),
('Creams'),
('Rice'),
('Squashes'),
('Cubes'),
('Soups'),
('Baby Shampoo'),
('Baby Oil'),
('Coffee'),
('Yogurt'),
('Desi Ghee'),
('Butter/Bread'),
('Tin Food'),
('Tea Bag'),
('Recipe Spices'),
('Vermicellis'),
('Wiz Bike Shampoo'),
('Wiz Car Shampoo'),
('WIZ Laundry'),
('Dall'),
('All/Own Brand/Raw Spices'),
('Sugar'),
('Dates'),
('Brit light'),
('Commodity Atta'),
('Baby Food'),
('Electric Bulbs/Solar Light'),
('Bed Sheets'),
('Jellies'),
('Cutlery'),
('Cream'),
('Oils'),
('All / Non Food / OTC Products'),
('Saintary Towels Etc'),
('All / Own Brand/Poly Shopping'),
('All/Own Brand/Poly Shopping Bags'),
('Frozen Food'),
('Burger'),
('PoS'),
('Powders'),
('Food'),
('All / Old Code'),
('Promotional Scheme Items'),
('Events'),
('All/Services'),
('All / Own Brand/Services'),
('All/Own Brand/Raw poly granual'),
('All / Non Food / Empty Bags'),
('Clothe Dresses'),
('Electronics'),
('Conf Miscellaneous'),
('Suji'),
('All / Non Food /OTC'),
('Atta'),
('All/Own Brand/RAW Spices'),
('Dishwash Gel'),
('Fresh Vegetables');

INSERT INTO generalfinance.genfin_products (categorie_id, product_name, price, stock_quantity, bar_code, quality) VALUES 
(1, 'Bread', 299, 50, '8901234567890', 1),
(1, 'Milk', 159, 30, '8901234567891', 1),
(2, 'Cheese', 499, 25, '8901234567892', 1),
(3, 'Cola', 199, 100, '8901234567893', 1),
(4, 'Chips', 99, 75, '8901234567894', 1),
(5, 'Detergent', 599, 40, '8901234567895', 1),
(6, 'Shampoo', 399, 60, '8901234567896', 1),
(7, 'Dog Food', 899, 20, '8901234567897', 1),
(8, 'Notebook', 149, 45, '8901234567898', 1),
(9, 'Screwdriver', 299, 15, '8901234567899', 1);

INSERT INTO `generalfinance`.`genfin_product` (product_name,price,stock_quantity,bar_code,quality,categorie_id_id) VALUES
("young b/b honey 200gm pouch (06)",355,10,"00000000",1,1),
...

SELECT COUNT(*) AS total_products 
FROM generalfinance.genfin_products;
SELECT * 
FROM generalfinance.genfin_products 
ORDER BY product_id DESC 
LIMIT 100;
DELETE FROM generalfinance.genfin_products;